routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Master\UserController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Master\LogController;
use App\Http\Controllers\ServerController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', [\App\Http\Controllers\StudentController::class, 'test'])->name('test');
Route::get('/reload-captcha', [App\Http\Controllers\StudentController::class, 'reloadCaptcha']);
Route::get('vote-off', function () {
    return view('vote-off');
})->name('vote-off');
Route::get('/', function () {
    return view('index');
})->name('index')->middleware('status-server');
Route::get('/login-student', [\App\Http\Controllers\StudentController::class, 'index'])->name('home.login')->middleware('status-server');
Route::post('/action/loginStudent', [\App\Http\Controllers\StudentController::class, 'actionLogin'])->name('actionLogin.student')->middleware('status-server');

Route::get('/vote-success', [\App\Http\Controllers\StudentController::class, 'vote_succes'])->name('vote.success')->middleware('status-server');
Route::middleware(['auth:voter', 'status-server'])->group(function () {
    Route::get('/vote', [\App\Http\Controllers\StudentController::class, 'vote'])->name('vote');
    Route::post('/action/voteCandidate', [\App\Http\Controllers\StudentController::class, 'actionVoteCandidate'])->name('actionVoteCandidate');
    Route::get('/logout', [\App\Http\Controllers\StudentController::class, 'logout'])->name('voter.logout');
    Route::get('/vote/not-valid', [\App\Http\Controllers\StudentController::class, 'notValid'])->name('vote.notValid');
});


Auth::routes([
    'register' => false
]);

Route::get('/nowDate', [\App\Http\Controllers\HomeController::class, 'nowDate'])->name('nowDate');

Route::middleware(['auth'])->group(function () {
});

Route::middleware(['auth:web'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard.home');

    Route::get('/announcement/calculate', [App\Http\Controllers\AnnouncementController::class, 'calculate'])->name('dashboard.announcement.calculate')->middleware('checkRole:admin');
    Route::get('/announcement/{saksiLengkap}', [App\Http\Controllers\AnnouncementController::class, 'index'])->name('dashboard.announcement')->middleware('checkRole:admin');

    // Master Student Routing
    Route::prefix('master')->name('master.')->group(function () {
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class);
        Route::get('/students/delete/{id}', [\App\Http\Controllers\Master\StudentController::class, 'destroy'])->name('students.delete')->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::get('/candidate/delete/{id}', [\App\Http\Controllers\Master\CandidateController::class, 'destroy'])->name('candidate.delete')->middleware('checkRole:admin');
        Route::get('/students/importExcel', [\App\Http\Controllers\Master\StudentController::class, 'importExcel'])->name('students.importExcel')->middleware('checkRole:admin');
        Route::post('/students/import', [\App\Http\Controllers\Master\StudentController::class, 'import'])->name('students.import')->middleware('checkRole:admin');
        Route::resource('students', \App\Http\Controllers\Master\StudentController::class)->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::resource('groups', \App\Http\Controllers\Master\GroupController::class)->middleware('checkRole:admin');
        Route::get('/groups/delete/{id}', [\App\Http\Controllers\Master\GroupController::class, 'destroy'])->name('groups.delete')->middleware('checkRole:admin');
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class)->middleware('checkRole:admin');
    });



    // Master Token Routing

    Route::prefix('feature')->name('feature.')->group(function () {
        Route::prefix('tokens')->name('tokens.')->group(function () {
            Route::get('/', [\App\Http\Controllers\Feature\TokenController::class, 'index'])->name('index')->middleware('checkRole:admin,token');
            Route::get('/updateToken', [\App\Http\Controllers\Feature\TokenController::class, 'update'])->name('update')->middleware('checkRole:admin,token');
            Route::post('/store', [\App\Http\Controllers\Feature\TokenController::class, 'store'])->name('store')->middleware('checkRole:admin,token');
            Route::get('/autocomplete', [\App\Http\Controllers\Feature\TokenController::class, 'autocomplete'])->name('autocomplete')->middleware('checkRole:admin,token');
            Route::get('/regenerate', [\App\Http\Controllers\Feature\TokenController::class, 'regenerate'])->name('regenerate')->middleware('checkRole:admin,token');
        });
    });


    // User Manager Routing
    Route::group(['prefix' => 'user-manager', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [UserController::class, 'index'])->name('user-manager.index');
        Route::post('/store', [UserController::class, 'store'])->name('user-manager.store');
        Route::get('/create', [UserController::class, 'create'])->name('user-manager.create');
        Route::get('/edit/{id}', [UserController::class, 'edit'])->name('user-manager.edit');
        Route::post('/update/{id}', [UserController::class, 'update'])->name('user-manager.update');
        Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('user-manager.delete');
    });

    // Logs Routing
    Route::group(['prefix' => 'logs', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [LogController::class, 'index'])->name('logs.index');
    });

    // server status
    Route::get('/server-status', [\App\Http\Controllers\ServerController::class, 'index'])->name('serverStatus')->middleware('checkRole:admin');
    Route::post('/server-status', [\App\Http\Controllers\ServerController::class, 'update'])->middleware('checkRole:admin');

    Route::get('/total-perangkatan', [\App\Http\Controllers\HomeController::class, 'totalPerangkatan'])->name('totalPerangkatan')->middleware('checkRole:admin,panwaslu,saksi');
    Route::get('/quick-count', [HomeController::class, 'quickCount'])->name('quickCount')->middleware('checkRole:admin');
});

Route::get('/testing', [ServerController::class, 'testing']);

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class Group extends Model
{
    use HasFactory;
    use SoftDeletes;
    use LogsActivity;

    protected $guarded = [];
    protected $dates = ['deleted_at'];


    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
}

app/Http/Controllers/Master/GroupController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Services\Group\GroupService;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public $studentService, $groupService;

    public function __construct(GroupService $groupService)
    {
        $this->groupService = $groupService;
    }

    public function index(Request $request)
    {
        if ($request->ajax()) {
            $dataTabel = $this->groupService->getDataTable(null);
            return $dataTabel;
        }

        return view('admin.contents.groups.index');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;

        view()->share([
            'data' => $data,
        ]);

        return view('admin.contents.groups.modal');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->groupService->store($request);

        return response()->json($data, 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->groupService->find($id);


        view()->share([
            'data' => $data,
        ]);

        return view('admin.contents.groups.modal');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->groupService->delete($id);
        return response()->json('success', 200);
    }
}

resources/views/admin/contents/groups/index.blade.php
@extends('layouts.admin')

@section('breadcrumb1','Group Manager')
@section('title_page','Groups')

@section('content')

@push('style')
@include('admin.components.datatable')

@include('admin.components.sweetalert')

@include('admin.components.select2')

<style>
    .swal-footer {
        text-align: center;
    }
</style>

@endpush


<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <h6>List - Group</h6>
                <a class="btn btn-warning" href="javascript:void(0)" id="createNewProduct"> Create</a>

            </div>
            @include('admin.components.message')
            <div class="card-body px-0 pt-0 pb-2">
                <div class="table-responsive p-3">
                    <table class="table align-items-center mb-0" id="item">
                        <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Group Name
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Action
                                </th>
                            </tr>
                        </thead>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="ajaxModel" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">

    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id="itemModal" name="itemModal"></div>
        </div>
    </div>

</div>

@push('script')


@endpush

@include('admin.contents.groups.js')

@endsection

resources/views/admin/contents/groups/js.blade.php
<script type="text/javascript">
    $(document).ready(function () {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        /* -------------- render datatables------------------------ */
        var table = $('#item').DataTable({
            language: {
                paginate: {
                    next: '<i class="fa fa-fw fa-long-arrow-right">',
                    previous: '<i class="fa fa-fw fa-long-arrow-left">'  
                }
            },
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{route('master.groups.index')}}",
            },
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                {
                    data: 'group_name',
                    name: 'group_name'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                },
            ]
        });

        window.refreshTable = function () {
            table.draw();
        }

        /* --------------  modal create------------------------ */
        $('#refresh').click(function () {
            window.parent.refreshTable();
        });

        $('#createNewProduct').click(function () {
            $('#itemModal').load('{{route('master.groups.create')}}');

            $('#ajaxModel').modal('show');
        });

        /* --------------  modal edit------------------------ */
        $('body').on('click', '.editProduct', function () {
            var data_id = $(this).data('id');
            $('#itemModal').load('{{route('master.groups.index')}}' + '/' + data_id + '/edit');

            $('#ajaxModel').modal('show');
        });


        /*------------------------------------------
       --------------------------------------------
       Delete Product Code
       --------------------------------------------
       --------------------------------------------*/
        $('body').on('click', '.deleteProduct', function () {

            var data_id = $(this).data('id');
            swal({
                title: "Are you sure?",
                // text: "",
                icon: "warning",
                buttons: [
                    'No, cancel it!',
                    'Yes, I am sure!'
                ],
                dangerMode: true,
            }).then(function (isConfirm) {
                if (isConfirm) {
                    swal({
                        title: 'Success!',
                        text: 'you have deleted data!',
                        icon: 'success'
                    }).then(function () {

                        $.ajax({
                            type: "get",
                            url: "{{route('master.groups.index')}}" + '/delete/' + data_id,
                            success: function (data) {
                                table.draw();
                            },
                            error: function (data) {
                                console.log('Error:', data);
                            }
                        });

                    });
                } else {
                    swal("Cancelled", "you cancel the action :)", "error");
                }
            })


        });

    });
</script>

resources/views/admin/contents/groups/modal.blade.php
<div class="alert alert-danger" style="display:none"></div>

<div class="modal-header" style="background-color: #2b3b98">
    <h4 class="modal-title text-white" id="modelHeading">Form</h4>
    <div class="block-options text-white">
        <a class="btn-block-option text-white" data-bs-dismiss="modal" aria-label="Close"
            style="background-color: transparent !important;">
            <i class="fa fa-fw fa-times"></i>
        </a>
    </div>
</div>


<form id="productForm" name="productForm" class="form-horizontal">
    <div class="modal-body">
        <input type="text" value="{{($data) ? $data->id :''}}" name="data_id" id="data_id"
            style="  visibility: hidden;">
        <div class="row">
            <div class="row push p-2">
                <div class="col-lg-12 col-xl-6">
                    <x-input type="text" name="group_name" label="Group Name"
                        value="{{($data) ? $data->group_name :''}}" placeholder="group_name" required=""
                        validateName="validate_group_name"></x-input>

                </div>
            </div>
        </div>
        <div class="block-content block-content-full text-end bg-body border-footer-modal">
            {{-- <a id="saveBtn" class="btn btn-sm btn-primary">Save</a>--}}
            <button type="button" id="saveBtn" class="btn btn-sm btn-success">Save</button>
            <a class="btn btn-sm btn-alt-secondary" data-bs-dismiss="modal">Back</a>
        </div>
    </div>
</form>


<script type="text/javascript">
    $(document).ready(function () {
        $('.select2').select2({
            placeholder: "Select",
            allowClear: true
        });


        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#saveBtn').val("create-product");
        $('#productForm').trigger("reset");



        /*---------------------------------------------
           --------------------------------------------
           Action Items
           --------------------------------------------
           --------------------------------------------*/
        $('#saveBtn').click(function (e) {
            e.preventDefault();
            console.log('testing data', $('#productForm').serialize());

            $.ajax({
                data: $('#productForm').serialize(),
                url: "{{ route('master.groups.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (result) {
                    console.log(result);
                    swal(
                        'Success!',
                        'You clicked the button!',
                        'success'
                    )
                    $('#productForm').trigger("reset");
                    $('#ajaxModel').modal('hide');

                    window.parent.refreshTable();

                    // location.reload();

                },
                error: function (result) {
                    // console.log(result);
                    if (result.responseJSON == undefined) {

                        $('#productForm').trigger("reset");
                        $('#ajaxModel').modal('hide');

                        window.parent.refreshTable();

                    } else {
                        var error = result.responseJSON.errors;

                        console.log(error);
                        //
                        if (error.group_name != undefined) {
                            $('#validate_group_name').html('*' + error.group_name[0]);
                        } else {
                            $('#validate_group_name').html('');
                        }
                    }


                }
            });
        });


    });
</script>