routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Master\UserController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Master\LogController;
use App\Http\Controllers\ServerController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', [\App\Http\Controllers\StudentController::class, 'test'])->name('test');
Route::get('/reload-captcha', [App\Http\Controllers\StudentController::class, 'reloadCaptcha']);
Route::get('vote-off', function () {
    return view('vote-off');
})->name('vote-off');
Route::get('/', function () {
    return view('index');
})->name('index')->middleware('status-server');
Route::get('/login-student', [\App\Http\Controllers\StudentController::class, 'index'])->name('home.login')->middleware('status-server');
Route::post('/action/loginStudent', [\App\Http\Controllers\StudentController::class, 'actionLogin'])->name('actionLogin.student')->middleware('status-server');

Route::get('/vote-success', [\App\Http\Controllers\StudentController::class, 'vote_succes'])->name('vote.success')->middleware('status-server');
Route::middleware(['auth:voter', 'status-server'])->group(function () {
    Route::get('/vote', [\App\Http\Controllers\StudentController::class, 'vote'])->name('vote');
    Route::post('/action/voteCandidate', [\App\Http\Controllers\StudentController::class, 'actionVoteCandidate'])->name('actionVoteCandidate');
    Route::get('/logout', [\App\Http\Controllers\StudentController::class, 'logout'])->name('voter.logout');
    Route::get('/vote/not-valid', [\App\Http\Controllers\StudentController::class, 'notValid'])->name('vote.notValid');
});


Auth::routes([
    'register' => false
]);

Route::get('/nowDate', [\App\Http\Controllers\HomeController::class, 'nowDate'])->name('nowDate');

Route::middleware(['auth'])->group(function () {
});

Route::middleware(['auth:web'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard.home');

    Route::get('/announcement/calculate', [App\Http\Controllers\AnnouncementController::class, 'calculate'])->name('dashboard.announcement.calculate')->middleware('checkRole:admin');
    Route::get('/announcement/{saksiLengkap}', [App\Http\Controllers\AnnouncementController::class, 'index'])->name('dashboard.announcement')->middleware('checkRole:admin');

    // Master Student Routing
    Route::prefix('master')->name('master.')->group(function () {
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class);
        Route::get('/students/delete/{id}', [\App\Http\Controllers\Master\StudentController::class, 'destroy'])->name('students.delete')->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::get('/candidate/delete/{id}', [\App\Http\Controllers\Master\CandidateController::class, 'destroy'])->name('candidate.delete')->middleware('checkRole:admin');
        Route::get('/students/importExcel', [\App\Http\Controllers\Master\StudentController::class, 'importExcel'])->name('students.importExcel')->middleware('checkRole:admin');
        Route::post('/students/import', [\App\Http\Controllers\Master\StudentController::class, 'import'])->name('students.import')->middleware('checkRole:admin');
        Route::resource('students', \App\Http\Controllers\Master\StudentController::class)->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::resource('groups', \App\Http\Controllers\Master\GroupController::class)->middleware('checkRole:admin');
        Route::get('/groups/delete/{id}', [\App\Http\Controllers\Master\GroupController::class, 'destroy'])->name('groups.delete')->middleware('checkRole:admin');
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class)->middleware('checkRole:admin');
    });



    // Master Token Routing

    Route::prefix('feature')->name('feature.')->group(function () {
        Route::prefix('tokens')->name('tokens.')->group(function () {
            Route::get('/', [\App\Http\Controllers\Feature\TokenController::class, 'index'])->name('index')->middleware('checkRole:admin,token');
            Route::get('/updateToken', [\App\Http\Controllers\Feature\TokenController::class, 'update'])->name('update')->middleware('checkRole:admin,token');
            Route::post('/store', [\App\Http\Controllers\Feature\TokenController::class, 'store'])->name('store')->middleware('checkRole:admin,token');
            Route::get('/autocomplete', [\App\Http\Controllers\Feature\TokenController::class, 'autocomplete'])->name('autocomplete')->middleware('checkRole:admin,token');
            Route::get('/regenerate', [\App\Http\Controllers\Feature\TokenController::class, 'regenerate'])->name('regenerate')->middleware('checkRole:admin,token');
        });
    });


    // User Manager Routing
    Route::group(['prefix' => 'user-manager', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [UserController::class, 'index'])->name('user-manager.index');
        Route::post('/store', [UserController::class, 'store'])->name('user-manager.store');
        Route::get('/create', [UserController::class, 'create'])->name('user-manager.create');
        Route::get('/edit/{id}', [UserController::class, 'edit'])->name('user-manager.edit');
        Route::post('/update/{id}', [UserController::class, 'update'])->name('user-manager.update');
        Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('user-manager.delete');
    });

    // Logs Routing
    Route::group(['prefix' => 'logs', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [LogController::class, 'index'])->name('logs.index');
    });

    // server status
    Route::get('/server-status', [\App\Http\Controllers\ServerController::class, 'index'])->name('serverStatus')->middleware('checkRole:admin');
    Route::post('/server-status', [\App\Http\Controllers\ServerController::class, 'update'])->middleware('checkRole:admin');

    Route::get('/total-perangkatan', [\App\Http\Controllers\HomeController::class, 'totalPerangkatan'])->name('totalPerangkatan')->middleware('checkRole:admin,panwaslu,saksi');
    Route::get('/quick-count', [HomeController::class, 'quickCount'])->name('quickCount')->middleware('checkRole:admin');
});

Route::get('/testing', [ServerController::class, 'testing']);

app/Models/Candidate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class Candidate extends Model
{

    use HasFactory;
    protected $guarded = [];    
    use LogsActivity;

    public function leader()
    {
        return $this->belongsTo(Student::class, 'candidate_lead');
    }
    public function vice()
    {
        return $this->belongsTo(Student::class, 'candidate_vice');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
}

app/Http/Controllers/Master/CandidateController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Http\Requests\CandidateRequest;
use App\Services\Candidate\CandidateService;
use App\Services\Student\StudentService;
use Illuminate\Http\Request;

class CandidateController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $candidateService;
    public $studentService;

    public function __construct(CandidateService $candidateService, StudentService $studentService)
    {
        $this->candidateService = $candidateService;
        $this->studentService = $studentService;
    }
    public function index(Request $request)
    {
        if($request->ajax()) {
            $dataTabel = $this->candidateService->getDataTable(null); // (Y/T)
//            dd($dataTabel);
            return $dataTabel;
        }

        return view('admin.contents.candidate.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;
        $students = $this->studentService->all();
        view()->share([
            'data' => $data,
            'students' => $students
        ]);
        return view('admin.contents.candidate.modal');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CandidateRequest $request)
    {
        $data = $this->candidateService->store($request);
        // dd($data);

        return response()->json('success',200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->candidateService->find($id);
        $students = $this->studentService->all();

        view()->share([
            'data' => $data,
            'students' => $students,
        ]);

        return view('admin.contents.candidate.modal');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->candidateService->delete($id);
        return response()->json('success',200);
        
    }
}

resources/views/admin/contents/candidate/index.blade.php
@extends('layouts.admin')

@section('breadcrumb1', 'Master')
@section('title_page', 'Candidate')

@section('content')

    @push('style')
        @include('admin.components.datatable')

        @include('admin.components.sweetalert')

        @include('admin.components.select2')

        <style>
            .select2-container--default .select2-selection--multiple .select2-selection__choice {
                background-color: #1648d6;
            }

            .select2-close-mask {
                z-index: 2099;
            }

            .select2-dropdown {
                z-index: 3051;
            }

            .swal-footer {
                text-align: center;
            }

            .select2-selection__rendered {
                line-height: 34px !important;
            }

            .select2-container .select2-selection--single {
                height: 39px !important;
            }

            .select2-selection__arrow {
                height: 34px !important;
            }
        </style>
    @endpush



    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>List - Candidate</h6>
                    <a class="btn btn-warning" href="javascript:void(0)" id="createNewProduct"> Create</a>

                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-3">
                        <table class="table align-items-center mb-0" id="item">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                        Candidate Number
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                        Candidate Leader</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                        Candidate vice</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                        Photo</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                        Vision</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                        Mission</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                        Action</th>
                                </tr>
                            </thead>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="ajaxModel" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">

        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div id="itemModal" name="itemModal"></div>
            </div>
        </div>

    </div>

    @push('script')
    @endpush

    @include('admin.contents.candidate.js')

@endsection

resources/views/admin/contents/candidate/js.blade.php
<script type="text/javascript">
    $(document).ready(function() {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        /* -------------- render datatables------------------------ */
        var table = $('#item').DataTable({
            language: {
                paginate: {
                    next: '<i class="fa fa-fw fa-long-arrow-right">',
                    previous: '<i class="fa fa-fw fa-long-arrow-left">'  
                }
            },
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('master.candidate.index') }}",
            },
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'number',
                    name: 'number'
                },
                {
                    data: 'candidate_lead',
                    name: 'leader.student_name'
                },
                {
                    data: 'candidate_vice',
                    name: 'vice.student_name'
                },
                {
                    data: 'photo',
                    name: 'photo',
                },
                {
                    data: 'visi',
                    name: 'visi',
                },
                {
                    data: 'mission',
                    name: 'mission',
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                },
            ]
        });

        window.refreshTable = function() {
            table.draw();
        }

        /* --------------  modal create------------------------ */
        $('#refresh').click(function() {
            window.parent.refreshTable();
        });

        $('#createNewProduct').click(function() {
            $('#itemModal').load('{{ route('master.candidate.create') }}');

            $('#ajaxModel').modal('show');
        });

        /* --------------  modal edit------------------------ */
        $('body').on('click', '.editProduct', function() {
            var data_id = $(this).data('id');
            $('#itemModal').load('{{ route('master.candidate.index') }}' + '/' + data_id + '/edit');
            $('#ajaxModel').modal('show');
        });

        /*------------------------------------------
       --------------------------------------------
       Delete Product Code
       --------------------------------------------
       --------------------------------------------*/
        $('body').on('click', '.deleteProduct', function() {

            var data_id = $(this).data('id');
            swal({
                title: "Are you sure?",
                // text: "",
                icon: "warning",
                buttons: [
                    'No, cancel it!',
                    'Yes, I am sure!'
                ],
                dangerMode: true,
            }).then(function(isConfirm) {
                if (isConfirm) {
                    swal({
                        title: 'Success!',
                        text: 'you have deleted data!',
                        icon: 'success'
                    }).then(function() {

                        $.ajax({
                            type: "get",
                            url: "{{ route('master.candidate.index') }}" +
                                '/delete/' + data_id,
                            success: function(data) {
                                table.draw();
                            },
                            error: function(data) {
                                console.log('Error:', data.responseText);
                            }
                        });

                    });
                } else {
                    swal("Cancelled", "you cancel the action :)", "error");
                }
            })


        });

    });
</script>

resources/views/admin/contents/candidate/modal.blade.php
<div class="alert alert-danger" style="display:none"></div>

<div class="modal-header" style="background-color: #2b3b98">
    <h4 class="modal-title text-white" id="modelHeading">Form</h4>
    <div class="block-options text-white">
        <a class="btn-block-option text-white" data-bs-dismiss="modal" aria-label="Close"
            style="background-color: transparent !important;">
            <i class="fa fa-fw fa-times"></i>
        </a>
    </div>
</div>

{{-- Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque itaque labore saepe quia reiciendis, ullam a nobis ex officia distinctio. --}}
<form id="productForm" name="productForm" class="form-horizontal" enctype="multipart/form-data">
    @csrf
    <div class="modal-body">
        <input type="text" value="{{ $data ? $data->id : '' }}" name="data_id" id="data_id"
            style="  visibility: hidden;">
        <div class="row">
            <div class="row push p-2">
                <div class="col-lg-12 col-xl-6">
                    <x-input type="text" name="number" label="Candidate Number"
                        value="{{ $data ? $data->number : '' }}" placeholder="candidate_number" required=""
                        validateName="validate_number"></x-input>
                    <div class="mb-4">
                        <label for="select2Multiple">Candidate Leader </label>
                        <div class="mb-4">
                            <select class="select2 form-control" name="candidate_lead" id="select2Lead">
                                @if ($data)
                                    <option value="{{ $data->candidate_lead }}" selected>
                                        {{ $data->leader == NULL ? "Kotak Kosong" : $data->leader->student_name }}
                                    </option>
                                @endif
                                @foreach ($students as $student)
                                    <option value="{{ $student->id }}">{{ $student->student_name }}</option>
                                @endforeach
                            </select>
                            <div style="color: red" id="validate_candidate_lead" name="validate_candidate_lead"></div>

                        </div>
                    </div>
                    <div class="mb-4">
                        <label for="select2Multiple">Candidate Vice </label>
                        <div class="mb-4">
                            <select class="select2 form-control" name="candidate_vice" id="select2Vice">
                                @if ($data)
                                    <option value="{{ $data->candidate_vice }}" selected>{{ $data->vice->student_name }}
                                    </option>
                                @endif
                                @foreach ($students as $student)
                                    <option value="{{ $student->id }}">{{ $student->student_name }}</option>
                                @endforeach
                            </select>
                            <div style="color: red" id="validate_candidate_vice" name="validate_candidate_vice"></div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-12 col-xl-6">
                    <div class="mb-4">
                        <label for="visi">Vision</label>
                        <textarea class="form-control" name="visi" id="visi" cols="30" rows="1"
                            validateName="validate_vision" required="" placeholder="Vision">{{ $data ? $data->visi : '' }}</textarea>
                    </div>
                    <div class="mb-4">
                        <label for="mission">Mission</label>
                        <textarea class="form-control" name="mission" id="mission" cols="30" rows="1"
                            validateName="validate_mission" required="" placeholder="Mission">{{ $data ? $data->mission : '' }}</textarea>
                    </div>

                    <div class="mb-4">
                        <label class="form-label" for="example-text-input">Photo</label>
                        <img src="{{ $data ? asset('storage/storage/assets_softUI/img/' . $data->photo) : '' }}"
                            class="img-preview img-fluid mb-3 col-sm-5 ">
                        <div class="mb-4">
                            <input type="file" class="form-control" name="photo" id="photo" value=""
                                placeholder="Photo of Candidate" onchange="previewImage()">
                            <div style="color: red" id="validate_photo" name="validate_photo"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="block-content block-content-full text-end bg-body border-footer-modal">
            {{--        <a id="saveBtn"  class="btn btn-sm btn-primary">Save</a> --}}
            <button type="submit" id="saveBtn" class="btn btn-sm btn-success">Save</button>
            <a class="btn btn-sm btn-alt-secondary" data-bs-dismiss="modal">Back</a>
        </div>
    </div>
</form>


<script type="text/javascript">
    // Preview Image 
    function previewImage() {
        var file = document.querySelector('input[type=file]').files[0];
        $('.img-preview').css('display', 'block')
        const reader = new FileReader();

        reader.addEventListener("load", () => {
            // preview.src = reader.result;
            $('.img-preview').attr('src', reader.result);
        }, false);

        // reader.onloadend = function(event) {
        //     $('.img-preview').attr('src', event.target.result);
        // }
        if (file) {
            reader.readAsDataURL(file);
        }
    }

    $(document).ready(function() {
        $('#select2Lead').select2({
            placeholder: "Select",
            allowClear: true
        });
        $('#select2Vice').select2({
            placeholder: "Select",
            allowClear: true
        });


        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#saveBtn').val("create-product");
        $('#productForm').trigger("reset");




        /*---------------------------------------------
           --------------------------------------------
           Action Items Create
           --------------------------------------------
           --------------------------------------------*/
        $('#saveBtn').on('click', function(e) {
            e.preventDefault();

            // var data = document.getElementById('productForm');
            var formData = new FormData($('#productForm')[0]);
            // console.log(formData);
            $.ajax({
                data: formData,
                type: 'POST',
                url: '{{ route('master.candidate.store') }}',
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
                success: function(result) {
                    // console.log(result);
                    swal(
                        'Success!',
                        'You clicked the button!',
                        'success'
                    )
                    $('#productForm').trigger("reset");
                    $('#ajaxModel').modal('hide');

                    window.parent.refreshTable();
                },
                error: function(result) {
                    console.log(result.responseText);
                    if (result.responseJSON == undefined) {

                        $('#productForm').trigger("reset");
                        $('#ajaxModel').modal('hide');

                        window.parent.refreshTable();

                    } else {
                        var error = result.responseJSON.errors;

                        console.log(error);
                        //
                        if (error.number != undefined) {
                            $('#validate_number').html('*' + error.number[0]);
                        } else {
                            $('#validate_number').html('');
                        }
                        //
                        if (error.candidate_lead != undefined) {
                            $('#validate_candidate_lead').html('*' + error.candidate_lead[
                                0]);
                        } else {
                            $('#validate_candidate_lead').html('');
                        }
                        //
                        if (error.candidate_vice != undefined) {
                            $('#validate_candidate_vice').html('*' + error.candidate_vice[
                                0]);
                        } else {
                            $('#validate_candidate_vice').html('');
                        }
                        //
                        if (error.visi != undefined) {
                            $('#validate_vision').html('*' + error.visi[0]);
                        } else {
                            $('#validate_vision').html('');
                        }
                        //
                        if (error.mission != undefined) {
                            $('#validate_mission').html('*' + error.mission[0]);
                        } else {
                            $('#validate_mission').html('');
                        }
                        //
                        if (error.photo != undefined) {
                            $('#validate_photo').html('*' + error.photo[0]);
                        } else {
                            $('#validate_photo').html('');
                        }
                    }
                }
            })
        });
    })
</script>