routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Master\UserController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Master\LogController;
use App\Http\Controllers\ServerController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', [\App\Http\Controllers\StudentController::class, 'test'])->name('test');
Route::get('/reload-captcha', [App\Http\Controllers\StudentController::class, 'reloadCaptcha']);
Route::get('vote-off', function () {
    return view('vote-off');
})->name('vote-off');
Route::get('/', function () {
    return view('index');
})->name('index')->middleware('status-server');
Route::get('/login-student', [\App\Http\Controllers\StudentController::class, 'index'])->name('home.login')->middleware('status-server');
Route::post('/action/loginStudent', [\App\Http\Controllers\StudentController::class, 'actionLogin'])->name('actionLogin.student')->middleware('status-server');

Route::get('/vote-success', [\App\Http\Controllers\StudentController::class, 'vote_succes'])->name('vote.success')->middleware('status-server');
Route::middleware(['auth:voter', 'status-server'])->group(function () {
    Route::get('/vote', [\App\Http\Controllers\StudentController::class, 'vote'])->name('vote');
    Route::post('/action/voteCandidate', [\App\Http\Controllers\StudentController::class, 'actionVoteCandidate'])->name('actionVoteCandidate');
    Route::get('/logout', [\App\Http\Controllers\StudentController::class, 'logout'])->name('voter.logout');
    Route::get('/vote/not-valid', [\App\Http\Controllers\StudentController::class, 'notValid'])->name('vote.notValid');
});


Auth::routes([
    'register' => false
]);

Route::get('/nowDate', [\App\Http\Controllers\HomeController::class, 'nowDate'])->name('nowDate');

Route::middleware(['auth'])->group(function () {
});

Route::middleware(['auth:web'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard.home');

    Route::get('/announcement/calculate', [App\Http\Controllers\AnnouncementController::class, 'calculate'])->name('dashboard.announcement.calculate')->middleware('checkRole:admin');
    Route::get('/announcement/{saksiLengkap}', [App\Http\Controllers\AnnouncementController::class, 'index'])->name('dashboard.announcement')->middleware('checkRole:admin');

    // Master Student Routing
    Route::prefix('master')->name('master.')->group(function () {
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class);
        Route::get('/students/delete/{id}', [\App\Http\Controllers\Master\StudentController::class, 'destroy'])->name('students.delete')->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::get('/candidate/delete/{id}', [\App\Http\Controllers\Master\CandidateController::class, 'destroy'])->name('candidate.delete')->middleware('checkRole:admin');
        Route::get('/students/importExcel', [\App\Http\Controllers\Master\StudentController::class, 'importExcel'])->name('students.importExcel')->middleware('checkRole:admin');
        Route::post('/students/import', [\App\Http\Controllers\Master\StudentController::class, 'import'])->name('students.import')->middleware('checkRole:admin');
        Route::resource('students', \App\Http\Controllers\Master\StudentController::class)->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::resource('groups', \App\Http\Controllers\Master\GroupController::class)->middleware('checkRole:admin');
        Route::get('/groups/delete/{id}', [\App\Http\Controllers\Master\GroupController::class, 'destroy'])->name('groups.delete')->middleware('checkRole:admin');
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class)->middleware('checkRole:admin');
    });



    // Master Token Routing

    Route::prefix('feature')->name('feature.')->group(function () {
        Route::prefix('tokens')->name('tokens.')->group(function () {
            Route::get('/', [\App\Http\Controllers\Feature\TokenController::class, 'index'])->name('index')->middleware('checkRole:admin,token');
            Route::get('/updateToken', [\App\Http\Controllers\Feature\TokenController::class, 'update'])->name('update')->middleware('checkRole:admin,token');
            Route::post('/store', [\App\Http\Controllers\Feature\TokenController::class, 'store'])->name('store')->middleware('checkRole:admin,token');
            Route::get('/autocomplete', [\App\Http\Controllers\Feature\TokenController::class, 'autocomplete'])->name('autocomplete')->middleware('checkRole:admin,token');
            Route::get('/regenerate', [\App\Http\Controllers\Feature\TokenController::class, 'regenerate'])->name('regenerate')->middleware('checkRole:admin,token');
        });
    });


    // User Manager Routing
    Route::group(['prefix' => 'user-manager', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [UserController::class, 'index'])->name('user-manager.index');
        Route::post('/store', [UserController::class, 'store'])->name('user-manager.store');
        Route::get('/create', [UserController::class, 'create'])->name('user-manager.create');
        Route::get('/edit/{id}', [UserController::class, 'edit'])->name('user-manager.edit');
        Route::post('/update/{id}', [UserController::class, 'update'])->name('user-manager.update');
        Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('user-manager.delete');
    });

    // Logs Routing
    Route::group(['prefix' => 'logs', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [LogController::class, 'index'])->name('logs.index');
    });

    // server status
    Route::get('/server-status', [\App\Http\Controllers\ServerController::class, 'index'])->name('serverStatus')->middleware('checkRole:admin');
    Route::post('/server-status', [\App\Http\Controllers\ServerController::class, 'update'])->middleware('checkRole:admin');

    Route::get('/total-perangkatan', [\App\Http\Controllers\HomeController::class, 'totalPerangkatan'])->name('totalPerangkatan')->middleware('checkRole:admin,panwaslu,saksi');
    Route::get('/quick-count', [HomeController::class, 'quickCount'])->name('quickCount')->middleware('checkRole:admin');
});

Route::get('/testing', [ServerController::class, 'testing']);

app/Models/Token.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class Token extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use LogsActivity;
    //    protected $guard = 'voter';

    protected $fillable = [
        'token',
        'student_id',
        'count',
        'expired_at',
    ];

    public function student()
    {
        return $this->belongsTo(Student::class);
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
}

app/Http/Controllers/Feature/TokenController.php
<?php

namespace App\Http\Controllers\Feature;

use App\Http\Controllers\Controller;
use App\Repositories\Student\StudentRepository;
use App\Services\Token\TokenService;
use Dflydev\DotAccessData\Data;
use Illuminate\Http\Request;

class TokenController extends Controller
{
    public $tokenService, $studentRepository;
    public function __construct(TokenService $tokenService, StudentRepository $studentRepository)
    {
        $this->tokenService = $tokenService;
        $this->studentRepository = $studentRepository;
    }

    public function index(Request $request)
    {



        if ($request->ajax()) {
            $dataTabel = $this->tokenService->getDataTable(null); // (Y/T)
            //            dd($dataTabel);
            return $dataTabel;
        }

        return view('admin.contents.tokens.index');
    }

    public function update(Request $request)
    {

        $data = $this->tokenService->updateToken($request->id);

        return response()->json('success', 200);
    }

    public function autocomplete(Request $request)
    {
        $data = [];

        if ($request->filled('q')) {
            $data = $this->studentRepository->search($request->get('q'));
        }

        return response()->json($data);
    }

    public function store(Request $request)
    {

        $data = $this->tokenService->store($request);
        // return redirect()->back()->with(($data['status']) ? 'success' : 'error', $data['message']);
        return response()->json([
            'status' => $data['status'],
            'message' => $data['message']
        ], ($data['status']) ? 200 : 400);
    }

    public function regenerate(Request $request)
    {
        $data = $this->tokenService->regenerate($request->id);

        return response()->json([
            'status' => $data['status'],
            'message' => $data['message']
        ], ($data['status']) ? 200 : 400);

        //        return response()->json('success',200);
    }
}

resources/views/admin/contents/tokens/index.blade.php
@extends('layouts.admin')

@section('breadcrumb1','Feature')
@section('title_page','Token')

@section('content')

@push('style')
@include('admin.components.datatable')

@include('admin.components.sweetalert')

@include('admin.components.select2')

<style>
    .swal-footer {
        text-align: center;
    }
</style>

@endpush



<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <h6>Create - Token</h6>

                {{-- <form action="{{route('feature.tokens.store')}}" method="post">--}}
                    <form id="itemForm" name="itemForm">
                        @csrf
                        <div class="row">
                            <div class="col-md-10 p-2">
                                <select class="select2 form-control" name="student_id" id="select2">


                                </select>
                            </div>
                            <div class="col-md-2 p-2">
                                <center>
                                    <button type="button" id="saveBtn" class="btn btn-warning" id="createNewProduct">
                                        Create</button>
                                </center>
                            </div>
                        </div>

                    </form>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <h6>List - Token</h6>


            </div>
            @include('admin.components.message')
            <div class="card-body px-0 pt-0 pb-2">
                <div class="table-responsive p-3">
                    <table class="table align-items-center mb-0" id="item">
                        <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">NRP
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Token</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Generate Status</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Duration Token</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Token time</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                    Action</th>
                            </tr>
                        </thead>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="ajaxModel" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">

    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id="itemModal" name="itemModal"></div>
        </div>
    </div>

</div>

@push('script')


@endpush

@include('admin.contents.tokens.js')

@endsection

resources/views/admin/contents/tokens/js.blade.php
<script type="text/javascript">
    $(document).ready(function() {

        function regenerate(id) {
            alert(id)
        }

        // $('.select2').select2({
        //     placeholder: "Select",
        //     allowClear: true
        // });

        $('.select2').select2({
            placeholder: 'Select an NRP',
            ajax: {
                url: "{{ route('feature.tokens.autocomplete') }}",
                dataType: 'json',
                delay: 250,
                processResults: function(data) {
                    return {
                        results: $.map(data, function(item) {
                            return {
                                text: item.student_nrp + ' - ' + item.student_name,
                                id: item.id
                            }
                        })
                    };
                },
                cache: true
            }
        });


        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        /* -------------- render datatables------------------------ */
        var table = $('#item').DataTable({
            language: {
                paginate: {
                    next: '<i class="fa fa-fw fa-long-arrow-right">',
                    previous: '<i class="fa fa-fw fa-long-arrow-left">'
                }
            },
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('feature.tokens.index') }}",
            },
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'student.student_nrp',
                    name: 'student.student_nrp'
                },
                {
                    data: 'token',
                    name: 'token'
                },
                {
                    data: 'count',
                    // name: 'count',
                    orderable: false
                },
                {
                    data: 'duration',
                    name: 'duration'
                },
                {
                    data: 'updated_at',
                    name: 'updated_at'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                },
            ],

            "drawCallback": function(settings, json) {

                // alert( 'DataTables has finished its initialisation.' );
                $('.timer').each(function(i) {
                    var timer = $(this);
                    var id = $(this).attr('data-id');
                    var dateNow = $(this).attr('data-dateNow');
                    var time_in_minutes = 5;
                    var current_time = Date.parse($(this).attr('data-create').replace(' ',
                        'T'));
                    // console.log(current_time);
                    var deadline = new Date(current_time + time_in_minutes * 60 * 1000);
                    var status = $(this).attr('data-status');

                    // console.log(deadline);

                    function time_remaining(endtime) {

                        var tmp = '';
                        // php 2023-03-24T03:33:27.483859Z is date format date
                        var t = Date.parse(endtime) - Date.parse(new Date());

                        var seconds = Math.floor((t / 1000) % 60);
                        var minutes = Math.floor((t / 1000 / 60) % 60);
                        var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
                        var days = Math.floor(t / (1000 * 60 * 60 * 24));
                        tmp = {
                            'total': t,
                            'days': days,
                            'hours': hours,
                            'minutes': minutes,
                            'seconds': seconds
                        };
                        // $.ajax({
                        //     // data: $('#itemForm').serialize(),
                        //     url: "{{ route('nowDate') }}",
                        //     type: "get",
                        //     dataType: 'json',
                        //     async: false,
                        //     global: false,
                        //     success: function (result) {


                        //     },

                        // });

                        // console.log(tmp);

                        return tmp

                    }

                    function run_clock(endtime) {

                        function update_clock() {
                            var t = time_remaining(endtime);
                            // console.log(t);
                            timer.text(t.minutes + 'm' + t.seconds + 's');
                            if (t.total <= 0) {
                                clearInterval(timeinterval);
                                timer.text("expired");
                                $.ajax({
                                    type: 'get',
                                    data: {
                                        id: id
                                    },
                                    url: "{{ route('feature.tokens.update') }}",
                                    success: function(data) {
                                        timer.prev().text('1');
                                    }
                                });
                            }

                            if (status == '1') {
                                timer.text("expired");
                            }

                        }
                        update_clock();
                        var timeinterval = setInterval(update_clock, 10000);
                    }
                    run_clock(deadline);
                });
            }
        });



        window.refreshTable = function() {
            table.draw();
        }

        $('#saveBtn').click(function(e) {
            e.preventDefault();
            let arr_select = ($('#select2').text()).split(' - ');
            arr_select[0] = arr_select[0].replace(/\s+/g, '');
            swal({
                title: "Are you sure?",
                text: `NRP : ${arr_select[0]}\n Name : ${arr_select[1]}`,
                icon: "warning",
                buttons: [
                    'No, cancel it!',
                    'Yes, I am sure!'
                ],
                dangerMode: true,
            }).then(function(isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        data: $('#itemForm').serialize(),
                        url: "{{ route('feature.tokens.store') }}",
                        type: "POST",
                        dataType: 'json',
                        success: function(result) {

                            swal(
                                'Success!',
                                'You clicked the button!',
                                'success'
                            )
                            $('#itemForm').trigger("reset");

                            window.parent.refreshTable();

                            // location.reload();

                        },
                        error: function(result) {
                            var response = JSON.parse(result.responseText);

                            swal(
                                'Error!',
                                response.message,
                                'error'
                            )
                            $('#itemForm').trigger("reset");
                            // if (result.responseJSON == undefined) {

                            //     $('#itemForm').trigger("reset");

                            // } else {
                            //     var error = result.responseJSON.errors;

                            //     console.log(error);
                            // }


                        }
                    });
                } else {
                    swal("Cancelled", "Cancel generates token", "error");
                }
                $('#select2').text('');
            });
        });

        $('body').on('click', '.regenerate', function() {

            var data_id = $(this).data('id');
            console.log($(this).data());
            swal({
                title: "Are you sure?",
                text: `NRP : ${$(this).data('nrp')}\n Name : ${$(this).data('name')}`,
                icon: "warning",
                buttons: [
                    'No, cancel it!',
                    'Yes, I am sure!'
                ],
                dangerMode: true,
            }).then(function(isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: "get",
                        url: "{{ route('feature.tokens.regenerate') }}",
                        data: {
                            id: data_id
                        },
                        success: function(data) {
                            swal(
                                'Success!',
                                'Berhasil Regenerate Token',
                                'success'
                            )
                            table.draw();
                            console.log(data);
                        },
                        error: function(data) {
                            console.log(data.responseJSON);
                            swal(
                                'Error!',
                                data.responseJSON.message,
                                'error'
                            )
                        }
                    });
                } else {
                    swal("Cancelled", "you cancel the action :)", "error");
                }
            })


        });




    });
</script>