routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Master\UserController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Master\LogController;
use App\Http\Controllers\ServerController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', [\App\Http\Controllers\StudentController::class, 'test'])->name('test');
Route::get('/reload-captcha', [App\Http\Controllers\StudentController::class, 'reloadCaptcha']);
Route::get('vote-off', function () {
    return view('vote-off');
})->name('vote-off');
Route::get('/', function () {
    return view('index');
})->name('index')->middleware('status-server');
Route::get('/login-student', [\App\Http\Controllers\StudentController::class, 'index'])->name('home.login')->middleware('status-server');
Route::post('/action/loginStudent', [\App\Http\Controllers\StudentController::class, 'actionLogin'])->name('actionLogin.student')->middleware('status-server');

Route::get('/vote-success', [\App\Http\Controllers\StudentController::class, 'vote_succes'])->name('vote.success')->middleware('status-server');
Route::middleware(['auth:voter', 'status-server'])->group(function () {
    Route::get('/vote', [\App\Http\Controllers\StudentController::class, 'vote'])->name('vote');
    Route::post('/action/voteCandidate', [\App\Http\Controllers\StudentController::class, 'actionVoteCandidate'])->name('actionVoteCandidate');
    Route::get('/logout', [\App\Http\Controllers\StudentController::class, 'logout'])->name('voter.logout');
    Route::get('/vote/not-valid', [\App\Http\Controllers\StudentController::class, 'notValid'])->name('vote.notValid');
});


Auth::routes([
    'register' => false
]);

Route::get('/nowDate', [\App\Http\Controllers\HomeController::class, 'nowDate'])->name('nowDate');

Route::middleware(['auth'])->group(function () {
});

Route::middleware(['auth:web'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard.home');

    Route::get('/announcement/calculate', [App\Http\Controllers\AnnouncementController::class, 'calculate'])->name('dashboard.announcement.calculate')->middleware('checkRole:admin');
    Route::get('/announcement/{saksiLengkap}', [App\Http\Controllers\AnnouncementController::class, 'index'])->name('dashboard.announcement')->middleware('checkRole:admin');

    // Master Student Routing
    Route::prefix('master')->name('master.')->group(function () {
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class);
        Route::get('/students/delete/{id}', [\App\Http\Controllers\Master\StudentController::class, 'destroy'])->name('students.delete')->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::get('/candidate/delete/{id}', [\App\Http\Controllers\Master\CandidateController::class, 'destroy'])->name('candidate.delete')->middleware('checkRole:admin');
        Route::get('/students/importExcel', [\App\Http\Controllers\Master\StudentController::class, 'importExcel'])->name('students.importExcel')->middleware('checkRole:admin');
        Route::post('/students/import', [\App\Http\Controllers\Master\StudentController::class, 'import'])->name('students.import')->middleware('checkRole:admin');
        Route::resource('students', \App\Http\Controllers\Master\StudentController::class)->middleware('checkRole:admin');
        Route::resource('candidate', \App\Http\Controllers\Master\CandidateController::class)->middleware('checkRole:admin');
        Route::resource('groups', \App\Http\Controllers\Master\GroupController::class)->middleware('checkRole:admin');
        Route::get('/groups/delete/{id}', [\App\Http\Controllers\Master\GroupController::class, 'destroy'])->name('groups.delete')->middleware('checkRole:admin');
        Route::resource('tokens', \App\Http\Controllers\Feature\TokenController::class)->middleware('checkRole:admin');
    });



    // Master Token Routing

    Route::prefix('feature')->name('feature.')->group(function () {
        Route::prefix('tokens')->name('tokens.')->group(function () {
            Route::get('/', [\App\Http\Controllers\Feature\TokenController::class, 'index'])->name('index')->middleware('checkRole:admin,token');
            Route::get('/updateToken', [\App\Http\Controllers\Feature\TokenController::class, 'update'])->name('update')->middleware('checkRole:admin,token');
            Route::post('/store', [\App\Http\Controllers\Feature\TokenController::class, 'store'])->name('store')->middleware('checkRole:admin,token');
            Route::get('/autocomplete', [\App\Http\Controllers\Feature\TokenController::class, 'autocomplete'])->name('autocomplete')->middleware('checkRole:admin,token');
            Route::get('/regenerate', [\App\Http\Controllers\Feature\TokenController::class, 'regenerate'])->name('regenerate')->middleware('checkRole:admin,token');
        });
    });


    // User Manager Routing
    Route::group(['prefix' => 'user-manager', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [UserController::class, 'index'])->name('user-manager.index');
        Route::post('/store', [UserController::class, 'store'])->name('user-manager.store');
        Route::get('/create', [UserController::class, 'create'])->name('user-manager.create');
        Route::get('/edit/{id}', [UserController::class, 'edit'])->name('user-manager.edit');
        Route::post('/update/{id}', [UserController::class, 'update'])->name('user-manager.update');
        Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('user-manager.delete');
    });

    // Logs Routing
    Route::group(['prefix' => 'logs', 'middleware' => 'checkRole:admin'], function () {
        Route::get('/', [LogController::class, 'index'])->name('logs.index');
    });

    // server status
    Route::get('/server-status', [\App\Http\Controllers\ServerController::class, 'index'])->name('serverStatus')->middleware('checkRole:admin');
    Route::post('/server-status', [\App\Http\Controllers\ServerController::class, 'update'])->middleware('checkRole:admin');

    Route::get('/total-perangkatan', [\App\Http\Controllers\HomeController::class, 'totalPerangkatan'])->name('totalPerangkatan')->middleware('checkRole:admin,panwaslu,saksi');
    Route::get('/quick-count', [HomeController::class, 'quickCount'])->name('quickCount')->middleware('checkRole:admin');
});

Route::get('/testing', [ServerController::class, 'testing']);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class Student extends Model
{
    use HasFactory;
    use SoftDeletes;
    use LogsActivity;

    protected $guarded = [];
    protected $dates = ['deleted_at'];


    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
}

app/Http/Controllers/Master/StudentController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Http\Requests\StudentRequest;
use App\Imports\StudentsImport;
use App\Services\Group\GroupService;
use App\Services\Student\StudentService;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public $studentService, $groupService;

    public function __construct(StudentService $studentService, GroupService $groupService)
    {
        $this->studentService = $studentService;
        $this->groupService = $groupService;
    }

    public function index(Request $request)
    {
        if ($request->ajax()) {
            $dataTabel = $this->studentService->getDataTable(null); // (Y/T)
            //            dd($dataTabel);
            return $dataTabel;
        }

        return view('admin.contents.students.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //        dd('dwq');

        $data = null;
        $groups = $this->groupService->all();


        view()->share([
            'data' => $data,
            'groups' => $groups
        ]);

        return view('admin.contents.students.modal');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentRequest $request)
    {
        $data = $this->studentService->store($request);
        //        dd($data);

        return response()->json('success', 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = $this->studentService->find($id);
        $groups = $this->groupService->all();


        view()->share([
            'data' => $data,
            'groups' => $groups
        ]);

        return view('admin.contents.students.modal');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->studentService->delete($id);
        return response()->json('success', 200);
    }

    public function importExcel()
    {
        $data = null;
        $groups = $this->groupService->all();


        view()->share([
            'data' => $data,
            'groups' => $groups
        ]);

        return view('admin.contents.students.import');
    }

    public function import(Request $request)
    {
        Excel::import(new StudentsImport($this->groupService), $request->file);
        return response()->json('success', 200);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Events\QuickCountUpdated;
use App\Http\Requests\LoginStudentRequest;
use App\Jobs\votingJob;
use App\Models\Candidate;
use App\Models\Token;
use App\Repositories\LoginStudent\LoginStudentRepository;
use App\Services\LoginStudent\LoginStudentService;
use App\Services\Student\StudentService;
use Faker\Factory as Faker;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use App\Services\Token\TokenService;
use Illuminate\Support\Carbon;
use App\Services\Encrypter\EncrypterService;

class StudentController extends Controller
{
    public $loginStudentService, $studentService, $tokenService, $encrypted, $loginRepository;

    public function __construct(LoginStudentService $loginStudentService, StudentService $studentService, TokenService $tokenService, EncrypterService $encrypted, LoginStudentRepository $loginRepository)
    {
        $this->loginStudentService = $loginStudentService;
        $this->studentService = $studentService;
        $this->encrypted = $encrypted;
        $this->tokenService = $tokenService;
        $this->loginRepository = $loginRepository;
    }

    public function index()
    {

        return view('login');
    }

    public function actionLogin(LoginStudentRequest $request)
    {
        $data = $this->loginStudentService->login($request);

        if ($data['status'] == 'success') {
            $data = $this->loginRepository->updateToken($data['data']['token']['id']);
            return redirect()->route('vote');
        } else {
            return redirect()->back()->with($data['status'], $data['message']);
        }
    }

    public function logoutLogActivity()
    {
        activity()
            ->causedBy(Auth::id())
            ->event('logout')
            ->log('logout');
        Auth::guard('voter')->logout();
    }


    public function vote()
    {

        $candidates = Candidate::with(['leader', 'vice'])->WhereNull('deleted_at')
            ->where('number', '!=', '0')
            ->orderBy('number', 'ASC')->get();
        $use_time = $this->tokenService->getByStudent(auth()->guard('voter')->user()->student->id)->use_time;
        // dd($use_time);
        $expired_time = Carbon::parse($use_time)->addMinutes(10);
        //        dd($candidates);
        view()->share([
            'expired_time' => $expired_time,
            'candidates' => $candidates
        ]);
        return view('vote');
    }

    public function vote_succes()
    {
        $this->logoutLogActivity();
        session()->flash('thank', '"Thank you for participating and voting in this election, your vote
                                is
                                very
                                valuable"');
        return view('vote_success');
    }

    public function logout()
    {
        $this->logoutLogActivity();
        return redirect()->route('home.login');
    }


    public function reloadCaptcha()
    {
        return response()->json(['captcha' => captcha_img('inverse')]);
    }

    public function actionVoteCandidate(Request $request)
    {
        $student_id = auth()->guard('voter')->user()->student->id;
        $token = $this->tokenService->getByStudent($student_id);
        if ($this->checkIfNotExpired($token->use_time) == false) {
            $this->notValid();
            return response()->json('expired', 200);
        } else {
            $encrypted = Crypt::encryptString((int)$request->candidate_id);
            $encrypted = $this->encrypted->encryptVote($encrypted);
            $vote = $this->studentService->votingAction($student_id, $encrypted);
            // event(new QuickCountUpdated('vote'));
            return response()->json('success', 200);
        }
    }

    public function notValid()
    {
        $id = auth()->guard('voter')->user()->student->id;
        $encrypted = Crypt::encryptString(0);
        $vote = $this->studentService->votingAction($id, $this->encrypted->encryptVote($encrypted));

        Auth::guard('voter')->logout();
        return redirect()->route('vote.success');
    }

    public function checkIfNotExpired(string $time): bool
    {
        // check if time is 10 minutes ago (yyyy-mm-dd hh:mm:ss)
        $time = strtotime($time);
        $now = strtotime(date('Y-m-d H:i:s'));
        $diff = $now - $time;
        // check if diff is less than 10 minutes
        if ($diff < 600) {
            return true;
        } else {
            return false;
        }
    }

    public function test()
    {

        $faker = Faker::create('id_ID');
        $encrypted = Crypt::encryptString($faker->numberBetween(1, 2));

        $job = new votingJob(1, $encrypted, $this->studentService);
        $this->dispatch($job);
    }
}

resources/views/admin/contents/students/import.blade.php
<div class="alert alert-danger" style="display:none"></div>

<div class="modal-header" style="background-color: #2b3b98">
    <h4 class="modal-title text-white" id="modelHeading">Form</h4>
    <div class="block-options text-white">
        <a class="btn-block-option text-white" data-bs-dismiss="modal" aria-label="Close"
            style="background-color: transparent !important;">
            <i class="fa fa-fw fa-times"></i>
        </a>
    </div>
</div>


<form id="productForm" name="productForm" class="form-horizontal" method="POST" enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="row push p-2">
                <div class="col-lg-12 col-xl-12">
                    <x-input
                        type="file" name="file" label="Students List File" value="" placeholder="file"
                        required="" id="file" validateName="validate_student"
                        accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
                        ></x-input>
                </div>
            </div>
        </div>
        <div class="block-content block-content-full text-end bg-body border-footer-modal">
            {{-- <a id="saveBtn" class="btn btn-sm btn-primary">Save</a> --}}
            <button type="button" id="saveBtn" class="btn btn-sm btn-success">Save</button>
            <a class="btn btn-sm btn-alt-secondary" data-bs-dismiss="modal">Back</a>
        </div>
    </div>
</form>


<script type="text/javascript">
    $(document).ready(function() {
        $('.select2').select2({
            placeholder: "Select",
            allowClear: true
        });


        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#saveBtn').val("import-product");
        $('#productForm').trigger("reset");



        /*---------------------------------------------
           --------------------------------------------
           Action Items
           --------------------------------------------
           --------------------------------------------*/
        $('#saveBtn').click(function(e) {
            e.preventDefault();
            const file = $('#productForm')[0][0]['files'][0];

            var form_data = new FormData();
            form_data.append('file', file);

            for (var pair of form_data.entries()) {
                console.log(pair[0] + ', ' + pair[1]);
            }

            $.ajax({
                url: "{{ route('master.students.import') }}",
                cache: false,
                contentType: false,
                processData: false,
                data: form_data,
                type: 'POST',
                dataType: "json",
                success: function(result) {
                    swal(
                        'Success!',
                        'You clicked the button!',
                        'success'
                    )
                    $('#productForm').trigger("reset");
                    $('#ajaxModel').modal('hide');

                    window.parent.refreshTable();

                    // location.reload();

                },
                error: function(result) {
                    console.log('result',result);
                    if (result.responseJSON == undefined) {

                        $('#productForm').trigger("reset");
                        $('#ajaxModel').modal('hide');

                        window.parent.refreshTable();

                    } else {
                        var error = result.responseJSON.errors;

                        console.log('error', error);
                    }


                }
            });
        });


    });
</script>

resources/views/admin/contents/students/js.blade.php
<script type="text/javascript">
    $(document).ready(function() {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        /* -------------- render datatables------------------------ */
        var table = $('#item').DataTable({
            language: {
                paginate: {
                    next: '<i class="fa fa-fw fa-long-arrow-right">',
                    previous: '<i class="fa fa-fw fa-long-arrow-left">'  
                }
            },
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('master.students.index') }}",
            },
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'student_nrp',
                    name: 'student_nrp'
                },
                {
                    data: 'student_name',
                    name: 'student_name'
                },
                {
                    data: 'group.group_name',
                    name: 'group.group_name'
                },
                {
                    data: 'status',
                    name: 'status'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                },
            ]
        });

        window.refreshTable = function() {
            table.draw();
        }

        /* --------------  modal create------------------------ */
        $('#refresh').click(function() {
            window.parent.refreshTable();
        });

        $('#createNewProduct').click(function() {
            $('#itemModal').load('{{ route('master.students.create') }}');

            $('#ajaxModel').modal('show');
        });

        /* --------------  modal import------------------------ */
        $('#importNewProduct').click(function () {
            $('#itemModal').load('{{route('master.students.importExcel')}}');

            $('#ajaxModel').modal('show');
        });

        /* --------------  modal edit------------------------ */
        $('body').on('click', '.editProduct', function() {
            var data_id = $(this).data('id');
            $('#itemModal').load('{{ route('master.students.index') }}' + '/' + data_id + '/edit');

            $('#ajaxModel').modal('show');
        });


        /*------------------------------------------
       --------------------------------------------
       Delete Product Code
       --------------------------------------------
       --------------------------------------------*/
        $('body').on('click', '.deleteProduct', function() {

            var data_id = $(this).data('id');
            swal({
                title: "Are you sure?",
                // text: "",
                icon: "warning",
                buttons: [
                    'No, cancel it!',
                    'Yes, I am sure!'
                ],
                dangerMode: true,
            }).then(function(isConfirm) {
                if (isConfirm) {
                    swal({
                        title: 'Success!',
                        text: 'you have deleted data!',
                        icon: 'success'
                    }).then(function() {

                        $.ajax({
                            type: "get",
                            url: "{{ route('master.students.index') }}" +
                                '/delete/' + data_id,
                            success: function(data) {
                                table.draw();
                            },
                            error: function(data) {
                                console.log('Error:', data);
                            }
                        });

                    });
                } else {
                    swal("Cancelled", "you cancel the action :)", "error");
                }
            })


        });

    });
</script>

resources/views/admin/contents/students/modal.blade.php
<div class="alert alert-danger" style="display:none"></div>

<div class="modal-header" style="background-color: #2b3b98">
    <h4 class="modal-title text-white" id="modelHeading">Form</h4>
    <div class="block-options text-white">
        <a class="btn-block-option text-white" data-bs-dismiss="modal" aria-label="Close" style="background-color: transparent !important;">
            <i class="fa fa-fw fa-times"></i>
        </a>
    </div>
</div>


<form id="productForm" name="productForm" class="form-horizontal">
    <div class="modal-body">
        <input type="text" value="{{($data) ? $data->id :''}}" name="data_id" id="data_id" style="  visibility: hidden;">
        <div class="row">
            <div class="row push p-2">
                <div class="col-lg-12 col-xl-6">
                    <x-input type="text" name="student_name" label="Student Name" value="{{($data) ? $data->student_name :''}}" placeholder="student_name" required="" validateName="validate_student_name"></x-input>
                    <x-input type="text" name="student_nrp" label="Student NRP" value="{{($data) ? $data->student_nrp :''}}" placeholder="student_nrp" required="" validateName="validate_student_nrp"></x-input>

                </div>
                <div class="col-lg-12 col-xl-6">

                    <div class="mb-4">
                        <label for="select2Multiple">Class </label>
                        <div class="mb-4">
                            <select class="select2 form-control" name="group_id" id="select2">
                                @if($data)
                                <option value="{{$data->group_id}}" selected>{{$data->group->group_name}}</option>
                                @endif
                                @foreach($groups as $group)
                                <option value="{{$group->id}}">{{$group->group_name}}</option>
                                @endforeach
                            </select>
                            <div style="color: red" id="validate_student_group" name="validate_student_group"></div>

                        </div>
                    </div>
                    <div class="mb-4">
                        <label for="select2Multiple">Status </label>
                        <div class="mb-4">
                            <select class="form-control" name="status">
                                <option value="no" {{($data) ? ($data->status == 'no') ? 'selected' : '' :''}}>No
                                </option>
                                <option value="yes" {{($data) ? ($data->status == 'yes') ? 'selected' : '' :''}}>Yes
                                </option>
                            </select>
                            <div style="color: red" id="validate_student_group" name="validate_student_group"></div>

                        </div>
                    </div>
                </div>


            </div>
        </div>
        <div class="block-content block-content-full text-end bg-body border-footer-modal">
            {{-- <a id="saveBtn" class="btn btn-sm btn-primary">Save</a>--}}
            <button type="button" id="saveBtn" class="btn btn-sm btn-success">Save</button>
            <a class="btn btn-sm btn-alt-secondary" data-bs-dismiss="modal">Back</a>
        </div>
    </div>
</form>


<script type="text/javascript">
    $(document).ready(function() {
        $('.select2').select2({
            placeholder: "Select",
            allowClear: true
        });


        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#saveBtn').val("create-product");
        $('#productForm').trigger("reset");



        /*---------------------------------------------
           --------------------------------------------
           Action Items
           --------------------------------------------
           --------------------------------------------*/
        $('#saveBtn').click(function(e) {
            e.preventDefault();

            $.ajax({
                data: $('#productForm').serialize(),
                url: "{{ route('master.students.store') }}",
                type: "POST",
                dataType: 'json',
                success: function(result) {
                    console.log(result);
                    swal(
                        'Success!',
                        'You clicked the button!',
                        'success'
                    )
                    $('#productForm').trigger("reset");
                    $('#ajaxModel').modal('hide');

                    window.parent.refreshTable();

                    // location.reload();

                },
                error: function(result) {
                    // console.log(result);
                    if (result.responseJSON == undefined) {

                        $('#productForm').trigger("reset");
                        $('#ajaxModel').modal('hide');

                        window.parent.refreshTable();

                    } else {
                        var error = result.responseJSON.errors;

                        console.log(error);
                        //
                        if (error.student_name != undefined) {
                            $('#validate_student_name').html('*' + error.student_name[0]);
                        } else {
                            $('#validate_student_name').html('');
                        }
                        //
                        if (error.student_nrp != undefined) {
                            $('#validate_student_nrp').html('*' + error.student_nrp[0]);
                        } else {
                            $('#validate_student_nrp').html('');
                        }
                        //
                        if (error.group_id != undefined) {
                            $('#validate_student_group').html('*' + error.group_id[0]);
                        } else {
                            $('#validate_student_group').html('');
                        }

                    }


                }
            });
        });


    });
</script>